# Generated by Django 5.0.9 on 2026-08-29 03:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('bfs', 'Breadth-First Search'), ('dfs', 'Depth-First Search'), ('dijkstra', "Dijkstra's Algorithm"), ('astar', 'A* Search'), ('greedy', 'Greedy Best-First Search'), ('bidirectional', 'Bidirectional BFS')], db_index=True, max_length=20)),
                ('grid_rows', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)])),
                ('grid_columns', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)])),
                ('nodes_visited', models.PositiveIntegerField()),
                ('path_length', models.PositiveIntegerField(default=0)),
                ('path_cost', models.PositiveIntegerField(default=0)),
                ('execution_time', models.DecimalField(decimal_places=3, help_text='Search duration in milliseconds, excluding animation.', max_digits=12)),
                ('path_found', models.BooleanField(default=True)),
                ('max_frontier_size', models.PositiveIntegerField(default=0)),
                ('maze_type', models.CharField(blank=True, choices=[('random', 'Random Obstacles'), ('division', 'Recursive Division'), ('backtracking', 'Recursive Backtracking'), ('prims', "Randomized Prim's")], max_length=20, null=True)),
                ('heuristic', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pathforge_visualization_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('grid_data', models.JSONField(help_text='{"rows": int, "cols": int, "walls": [int], "weights": [int]}')),
                ('start_position', models.JSONField(help_text='{"row": int, "col": int}')),
                ('target_position', models.JSONField(help_text='{"row": int, "col": int}')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pathforge_saved_grid',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='grid_user_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedgrid',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_grid_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='visualizationrun',
            index=models.Index(fields=['user', '-created_at'], name='run_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='visualizationrun',
            index=models.Index(fields=['user', 'algorithm'], name='run_user_algorithm_idx'),
        ),
        migrations.AddConstraint(
            model_name='visualizationrun',
            constraint=models.CheckConstraint(check=models.Q(('grid_rows__gte', 2), ('grid_columns__gte', 2)), name='run_board_min_size'),
        ),
    ]
